import { drizzle } from "drizzle-orm/mysql2";
import { venues } from "./drizzle/schema.js";

const db = drizzle(process.env.DATABASE_URL);

const venuesData = [
  // Wedding Venues
  {
    name: "The Deep",
    slug: "the-deep",
    description: "Make your special day truly unforgettable at The Deep, one of the UK's most spectacular aquariums. Exchange vows surrounded by thousands of marine creatures in our stunning underwater tunnel, then celebrate in our elegant event spaces with panoramic views of the Humber estuary. Our dedicated events team will ensure every detail is perfect, from the ceremony to the reception.",
    category: "Wedding",
    capacity: 200,
    address: "Tower Street, Hull, HU1 4DP",
    latitude: "53.7443",
    longitude: "-0.3315",
    amenities: JSON.stringify([
      "Underwater ceremony venue",
      "Licensed bar",
      "In-house catering",
      "Waterfront views",
      "Exclusive hire available",
      "Dedicated event coordinator",
      "Audio-visual equipment",
      "Accessible facilities"
    ]),
    pricing: "From £5,000 for exclusive venue hire",
    imageUrl: "/images/venue_wedding.png",
    website: "https://www.thedeep.co.uk",
    phone: "01482 381000",
    email: "events@thedeep.co.uk",
    featured: true,
  },
  {
    name: "The Guildhall",
    slug: "the-guildhall",
    description: "Step into history at The Guildhall, Hull's most prestigious wedding venue. This stunning Grade II* listed building features magnificent Victorian architecture, ornate ceilings, and elegant chandeliers. The Grand Hall provides a breathtaking backdrop for ceremonies and receptions, accommodating up to 350 guests. Perfect for couples seeking a traditional, sophisticated wedding venue in the heart of Hull.",
    category: "Wedding",
    capacity: 350,
    address: "Alfred Gelder Street, Hull, HU1 2AA",
    latitude: "53.7446",
    longitude: "-0.3367",
    amenities: JSON.stringify([
      "Historic Victorian architecture",
      "Grand Hall with chandeliers",
      "Licensed for ceremonies",
      "Professional catering kitchen",
      "Bridal suite",
      "Stage and dance floor",
      "Central location",
      "Parking nearby"
    ]),
    pricing: "From £3,500 for full day hire",
    imageUrl: "/images/venue_wedding.png",
    website: "https://www.hull.gov.uk",
    phone: "01482 300300",
    email: "guildhall@hullcc.gov.uk",
    featured: true,
  },
  {
    name: "Doubletree Hilton Hull",
    slug: "doubletree-hilton-hull",
    description: "Experience luxury and elegance at the Doubletree Hilton Hull. Our contemporary hotel offers stunning waterfront views and exceptional service for your special day. The elegant ballroom can accommodate up to 200 guests, while our experienced wedding team ensures every detail is perfect. Enjoy modern amenities, delicious cuisine, and comfortable accommodation for you and your guests.",
    category: "Wedding",
    capacity: 200,
    address: "Ferensway, Hull, HU2 8LN",
    latitude: "53.7453",
    longitude: "-0.3426",
    amenities: JSON.stringify([
      "Waterfront location",
      "Modern ballroom",
      "Licensed bar",
      "Award-winning catering",
      "Guest accommodation",
      "Bridal suite",
      "Free Wi-Fi",
      "Dedicated wedding coordinator"
    ]),
    pricing: "From £4,000 for ceremony and reception",
    imageUrl: "/images/venue_wedding.png",
    website: "https://www.hilton.com",
    phone: "01482 380100",
    email: "weddings.hull@hilton.com",
    featured: false,
  },
  {
    name: "Pearson Park Conservatory",
    slug: "pearson-park-conservatory",
    description: "Celebrate your wedding in the enchanting Pearson Park Conservatory, a beautiful Victorian glasshouse nestled in one of Hull's most picturesque parks. This unique venue offers a romantic garden setting with lush greenery and natural light flooding through the glass roof. Perfect for intimate ceremonies and receptions, accommodating up to 80 guests in a truly magical atmosphere.",
    category: "Wedding",
    capacity: 80,
    address: "Pearson Park, Hull, HU5 2TD",
    latitude: "53.7567",
    longitude: "-0.3534",
    amenities: JSON.stringify([
      "Victorian glasshouse",
      "Garden setting",
      "Natural lighting",
      "Licensed for ceremonies",
      "Park surroundings for photos",
      "Intimate atmosphere",
      "Accessible location",
      "Parking available"
    ]),
    pricing: "From £1,500 for venue hire",
    imageUrl: "/images/venue_wedding.png",
    website: "https://www.hull.gov.uk",
    phone: "01482 300300",
    email: "parks@hullcc.gov.uk",
    featured: false,
  },
  {
    name: "The Kingston Theatre Hotel",
    slug: "the-kingston-theatre-hotel",
    description: "Experience theatrical elegance at The Kingston Theatre Hotel, a unique boutique venue in Hull's city center. This beautifully restored building combines Victorian charm with modern luxury, offering an intimate setting for weddings up to 120 guests. The stunning function room features original architectural details, while our dedicated team provides personalized service to make your day unforgettable.",
    category: "Wedding",
    capacity: 120,
    address: "Kingston Square, Hull, HU1 3HF",
    latitude: "53.7442",
    longitude: "-0.3378",
    amenities: JSON.stringify([
      "Boutique hotel setting",
      "Victorian architecture",
      "Licensed bar",
      "In-house catering",
      "Guest accommodation",
      "City center location",
      "Personalized service",
      "Elegant function room"
    ]),
    pricing: "From £2,800 for full day hire",
    imageUrl: "/images/venue_wedding.png",
    website: "https://www.kingstontheatrehotel.com",
    phone: "01482 225828",
    email: "events@kingstontheatrehotel.com",
    featured: false,
  },

  // Conference Venues
  {
    name: "MKM Stadium (Hull City)",
    slug: "mkm-stadium",
    description: "Host your conference at the MKM Stadium, Hull's premier sports and events venue. With over 750 square meters of flexible conference space, we can accommodate events from 10 to 1,000 delegates. Our state-of-the-art facilities include multiple meeting rooms, a large auditorium, and executive boxes with pitch views. Perfect for conferences, exhibitions, seminars, and large-scale corporate events.",
    category: "Conference",
    capacity: 1000,
    address: "The Circle, Walton Street, Hull, HU3 6HU",
    latitude: "53.7461",
    longitude: "-0.3679",
    amenities: JSON.stringify([
      "750+ sqm conference space",
      "Multiple meeting rooms",
      "Auditorium seating",
      "Executive boxes",
      "Audio-visual equipment",
      "High-speed Wi-Fi",
      "On-site catering",
      "Ample parking",
      "Accessible facilities"
    ]),
    pricing: "From £500 per day for meeting rooms",
    imageUrl: "/images/venue_conference.png",
    website: "https://www.mkmstadium.com",
    phone: "01482 358882",
    email: "events@hullcityafc.net",
    featured: true,
  },
  {
    name: "Connexin Live Hull",
    slug: "connexin-live-hull",
    description: "Experience cutting-edge conference facilities at Connexin Live Hull, located in the heart of Hull City Centre. Our versatile venue offers modern meeting spaces equipped with the latest technology, perfect for conferences, seminars, and business events. With flexible room configurations and professional support staff, we can accommodate events from 10 to 500 delegates in a contemporary setting.",
    category: "Conference",
    capacity: 500,
    address: "Kingston Street, Hull, HU1 2DW",
    latitude: "53.7438",
    longitude: "-0.3362",
    amenities: JSON.stringify([
      "Modern conference facilities",
      "Flexible room layouts",
      "Advanced AV technology",
      "High-speed internet",
      "Professional sound system",
      "On-site technical support",
      "Catering services",
      "City center location",
      "Public transport links"
    ]),
    pricing: "From £400 per day",
    imageUrl: "/images/venue_conference.png",
    website: "https://connexinlivehull.com",
    phone: "01482 300300",
    email: "events@connexinlive.com",
    featured: true,
  },
  {
    name: "University of Hull - Canham Turner",
    slug: "university-hull-canham-turner",
    description: "The Canham Turner Building at the University of Hull offers professional conference facilities in a modern academic setting. Our purpose-built venue features lecture theaters, seminar rooms, and exhibition spaces, all equipped with state-of-the-art technology. Ideal for academic conferences, training sessions, and corporate events, with capacity for up to 300 delegates.",
    category: "Conference",
    capacity: 300,
    address: "Cottingham Road, Hull, HU6 7RX",
    latitude: "53.7705",
    longitude: "-0.3668",
    amenities: JSON.stringify([
      "Lecture theaters",
      "Seminar rooms",
      "Exhibition space",
      "Advanced AV equipment",
      "Video conferencing",
      "Wi-Fi throughout",
      "Catering facilities",
      "Campus parking",
      "Accessible venue"
    ]),
    pricing: "From £300 per day",
    imageUrl: "/images/venue_conference.png",
    website: "https://www.hull.ac.uk",
    phone: "01482 346311",
    email: "hospitality@hull.ac.uk",
    featured: false,
  },
  {
    name: "Holiday Inn Hull Marina",
    slug: "holiday-inn-hull-marina",
    description: "Host your conference at the Holiday Inn Hull Marina, offering modern meeting facilities with stunning marina views. Our flexible conference rooms can accommodate up to 150 delegates, with professional event planning support and comprehensive catering services. Perfect for business meetings, training days, and corporate conferences in a convenient waterfront location.",
    category: "Conference",
    capacity: 150,
    address: "Castle Street, Hull, HU1 2BX",
    latitude: "53.7434",
    longitude: "-0.3298",
    amenities: JSON.stringify([
      "Marina views",
      "Flexible meeting rooms",
      "Professional AV equipment",
      "High-speed Wi-Fi",
      "Business center",
      "On-site restaurant",
      "Guest accommodation",
      "Parking available"
    ]),
    pricing: "From £350 per day",
    imageUrl: "/images/venue_conference.png",
    website: "https://www.ihg.com",
    phone: "01482 382520",
    email: "meetings.hullmarina@ihg.com",
    featured: false,
  },

  // Corporate Event Venues
  {
    name: "Hull City Hall",
    slug: "hull-city-hall",
    description: "Make a statement at Hull City Hall, the city's most prestigious corporate event venue. This magnificent Grade II listed building offers elegant spaces for corporate dinners, award ceremonies, and gala events. The Grand Hall features stunning architecture and can accommodate up to 400 guests for seated dinners. Our experienced events team ensures flawless execution of your corporate function.",
    category: "Corporate",
    capacity: 400,
    address: "Queen Victoria Square, Hull, HU1 3RQ",
    latitude: "53.7435",
    longitude: "-0.3382",
    amenities: JSON.stringify([
      "Historic architecture",
      "Grand Hall",
      "Professional staging",
      "Licensed bar",
      "Catering kitchen",
      "Audio-visual equipment",
      "Accessible facilities",
      "Central location"
    ]),
    pricing: "From £2,000 for evening hire",
    imageUrl: "/images/venue_corporate.png",
    website: "https://www.hull.gov.uk",
    phone: "01482 300300",
    email: "cityhall@hullcc.gov.uk",
    featured: true,
  },
  {
    name: "Humber Street Gallery",
    slug: "humber-street-gallery",
    description: "Host your corporate event at Humber Street Gallery, a contemporary art space in Hull's vibrant Fruit Market district. Our modern venue offers a unique setting for product launches, networking events, and corporate receptions. With flexible gallery spaces and stunning waterfront views, we provide a creative backdrop for memorable corporate functions up to 200 guests.",
    category: "Corporate",
    capacity: 200,
    address: "64 Humber Street, Hull, HU1 1TU",
    latitude: "53.7425",
    longitude: "-0.3285",
    amenities: JSON.stringify([
      "Contemporary gallery space",
      "Waterfront location",
      "Flexible layout",
      "Modern facilities",
      "Licensed bar",
      "Catering options",
      "Natural lighting",
      "Trendy Fruit Market area"
    ]),
    pricing: "From £800 for evening hire",
    imageUrl: "/images/venue_corporate.png",
    website: "https://www.humberstreetgallery.co.uk",
    phone: "01482 323484",
    email: "info@humberstreetgallery.co.uk",
    featured: true,
  },
  {
    name: "The Royal Hotel Hull",
    slug: "the-royal-hotel-hull",
    description: "Experience timeless elegance at The Royal Hotel Hull, offering sophisticated spaces for corporate events and business functions. Our historic hotel features beautifully appointed function rooms, perfect for corporate dinners, meetings, and networking events. With capacity for up to 180 guests and full catering services, we provide a professional setting in the heart of Hull.",
    category: "Corporate",
    capacity: 180,
    address: "170 Ferensway, Hull, HU1 3UF",
    latitude: "53.7448",
    longitude: "-0.3412",
    amenities: JSON.stringify([
      "Historic hotel setting",
      "Multiple function rooms",
      "Professional catering",
      "Licensed bar",
      "Audio-visual equipment",
      "Guest accommodation",
      "City center location",
      "Dedicated events team"
    ]),
    pricing: "From £1,200 for full day hire",
    imageUrl: "/images/venue_corporate.png",
    website: "https://www.theroyalhotelhull.com",
    phone: "01482 325087",
    email: "events@theroyalhotelhull.com",
    featured: false,
  },
  {
    name: "Village Hotel Hull",
    slug: "village-hotel-hull",
    description: "Host your corporate event at Village Hotel Hull, offering modern facilities and excellent amenities. Our versatile event spaces can accommodate corporate meetings, training sessions, and team-building events for up to 120 delegates. With on-site leisure facilities, accommodation, and professional catering, we provide everything you need for successful corporate functions.",
    category: "Corporate",
    capacity: 120,
    address: "Henry Boot Way, Hull, HU4 7DY",
    latitude: "53.7589",
    longitude: "-0.3892",
    amenities: JSON.stringify([
      "Modern meeting rooms",
      "Leisure facilities",
      "Swimming pool and gym",
      "Guest accommodation",
      "Restaurant and bar",
      "Free parking",
      "Wi-Fi throughout",
      "Team building activities"
    ]),
    pricing: "From £600 per day",
    imageUrl: "/images/venue_corporate.png",
    website: "https://www.village-hotels.co.uk",
    phone: "01482 356800",
    email: "hull.events@village-hotels.com",
    featured: false,
  },

  // Party Venues
  {
    name: "The Goodfellowship",
    slug: "the-goodfellowship",
    description: "Celebrate in style at The Goodfellowship, Hull's premier party venue. Our vibrant space features a large dance floor, professional sound and lighting systems, and a fully stocked bar. Perfect for birthday parties, anniversaries, and celebrations, we can accommodate up to 250 guests. Our experienced team will help create an unforgettable party atmosphere for your special occasion.",
    category: "Party",
    capacity: 250,
    address: "Goodfellowship Lane, Hull, HU6 7RX",
    latitude: "53.7698",
    longitude: "-0.3645",
    amenities: JSON.stringify([
      "Large dance floor",
      "Professional DJ booth",
      "Sound and lighting system",
      "Licensed bar",
      "Outdoor terrace",
      "Flexible layout",
      "Catering available",
      "Free parking"
    ]),
    pricing: "From £500 for evening hire",
    imageUrl: "/images/venue_party.png",
    website: "https://www.thegoodfellowship.co.uk",
    phone: "01482 447788",
    email: "info@thegoodfellowship.co.uk",
    featured: true,
  },
  {
    name: "The Lodge Bar and Grill",
    slug: "the-lodge-bar-and-grill",
    description: "Host your party at The Lodge Bar and Grill, a stylish venue offering a perfect blend of dining and entertainment. Our modern space features a restaurant area, bar, and party room with capacity for up to 150 guests. Ideal for birthday celebrations, engagement parties, and social gatherings, with delicious food and drinks in a lively atmosphere.",
    category: "Party",
    capacity: 150,
    address: "Princes Avenue, Hull, HU5 3QA",
    latitude: "53.7523",
    longitude: "-0.3489",
    amenities: JSON.stringify([
      "Restaurant and bar",
      "Private party room",
      "Dance floor",
      "Sound system",
      "Full catering menu",
      "Cocktail bar",
      "Outdoor seating",
      "Central location"
    ]),
    pricing: "From £400 for evening hire",
    imageUrl: "/images/venue_party.png",
    website: "https://www.thelodgebarandgrill.co.uk",
    phone: "01482 447474",
    email: "bookings@thelodgebarandgrill.co.uk",
    featured: true,
  },
  {
    name: "Minerva Masonic Hall",
    slug: "minerva-masonic-hall",
    description: "Celebrate your special occasion at Minerva Masonic Hall, a unique and elegant party venue in Hull. Our historic building offers beautiful function rooms with period features, perfect for milestone birthdays, anniversaries, and family celebrations. With capacity for up to 200 guests and flexible catering options, we provide a memorable setting for your party.",
    category: "Party",
    capacity: 200,
    address: "Jarratt Street, Hull, HU1 3HB",
    latitude: "53.7447",
    longitude: "-0.3356",
    amenities: JSON.stringify([
      "Historic building",
      "Elegant function rooms",
      "Licensed bar",
      "Catering kitchen",
      "Dance floor",
      "Stage area",
      "Parking nearby",
      "Accessible facilities"
    ]),
    pricing: "From £350 for evening hire",
    imageUrl: "/images/venue_party.png",
    website: "https://www.minervamasonic.co.uk",
    phone: "01482 223344",
    email: "bookings@minervamasonic.co.uk",
    featured: false,
  },
  {
    name: "Sewell Group Craven Park",
    slug: "sewell-group-craven-park",
    description: "Experience something different at Sewell Group Craven Park, home of Hull KR. Our sports venue offers unique party spaces including executive boxes and function suites, perfect for sports-themed parties and celebrations. With capacity for up to 300 guests, professional catering, and a lively atmosphere, we provide an exciting venue for memorable parties.",
    category: "Party",
    capacity: 300,
    address: "Preston Road, Hull, HU9 5HE",
    latitude: "53.7512",
    longitude: "-0.2987",
    amenities: JSON.stringify([
      "Sports venue setting",
      "Executive boxes",
      "Function suites",
      "Licensed bars",
      "Catering services",
      "Audio-visual equipment",
      "Ample parking",
      "Pitch views"
    ]),
    pricing: "From £600 for evening hire",
    imageUrl: "/images/venue_party.png",
    website: "https://www.hullkr.co.uk",
    phone: "01482 788850",
    email: "events@hullkr.co.uk",
    featured: false,
  },

  // Exhibition Venues
  {
    name: "Hull Venue - Exhibition Centre",
    slug: "hull-venue-exhibition-centre",
    description: "Hull's purpose-built exhibition center offers over 2,000 square meters of flexible space for trade shows, exhibitions, and large-scale events. Our modern facility features high ceilings, excellent natural light, and state-of-the-art facilities. With professional event support and easy access, we can accommodate exhibitions from 500 to 2,000 visitors.",
    category: "Exhibition",
    capacity: 2000,
    address: "Walton Street, Hull, HU3 6HU",
    latitude: "53.7458",
    longitude: "-0.3685",
    amenities: JSON.stringify([
      "2,000+ sqm exhibition space",
      "High ceilings",
      "Natural lighting",
      "Loading bay access",
      "Professional rigging points",
      "Catering facilities",
      "Wi-Fi throughout",
      "Ample parking"
    ]),
    pricing: "From £2,500 per day",
    imageUrl: "/images/hull_venues.png",
    website: "https://www.hullvenue.co.uk",
    phone: "01482 300400",
    email: "exhibitions@hullvenue.co.uk",
    featured: true,
  },

  // Concert Venues
  {
    name: "Hull City Hall - Concert Hall",
    slug: "hull-city-hall-concerts",
    description: "Experience world-class acoustics at Hull City Hall's Concert Hall, one of the UK's finest music venues. Our historic auditorium seats 1,400 and has hosted legendary performers for over 90 years. With excellent sightlines, professional sound and lighting, and a dedicated events team, we provide the perfect setting for concerts, shows, and live performances.",
    category: "Concert",
    capacity: 1400,
    address: "Queen Victoria Square, Hull, HU1 3RQ",
    latitude: "53.7435",
    longitude: "-0.3382",
    amenities: JSON.stringify([
      "Historic concert hall",
      "1,400 seat auditorium",
      "Professional acoustics",
      "Stage and backstage facilities",
      "Licensed bars",
      "Box office",
      "Accessible seating",
      "City center location"
    ]),
    pricing: "POA for concert bookings",
    imageUrl: "/images/hull_venues.png",
    website: "https://www.hulltheatres.co.uk",
    phone: "01482 300306",
    email: "boxoffice@hullcc.gov.uk",
    featured: true,
  },
];

async function seedVenues() {
  console.log("Starting venue seeding...");
  
  try {
    for (const venue of venuesData) {
      await db.insert(venues).values(venue);
      console.log(`✓ Added venue: ${venue.name}`);
    }
    
    console.log(`\n✅ Successfully seeded ${venuesData.length} venues!`);
  } catch (error) {
    console.error("Error seeding venues:", error);
    process.exit(1);
  }
  
  process.exit(0);
}

seedVenues();
